projects/mysite/model_test/urls.py
__author__ = 'YI'

from django.conf.urls import patterns, url
#from model_test import views

urlpatterns = patterns('',url(r'^/?$','model_test.views.index'))

projects/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/',include('polls.urls',namespace='polls')),
    url(r'^model_test',include('model_test.urls'))
)

projects/mysite/polls/urls.py
__author__ = 'db'

from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<poll_id>\d+)/results/?$', views.results, name='results'),
                       url(r'(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
                       url(r'(?P<poll_id>\d+)/details$', views.details, name='details')
)

projects/mysite/model_test/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)


class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)


class Album(models.Model):
    artist = models.ForeignKey(Musician)
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    num_stars = models.IntegerField()

projects/mysite/myapp/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=20)
    age = models.IntegerField(max_length=2)

projects/mysite/polls/models.py
import datetime

from django.utils import timezone

from django.db import models

# Create your models here.
class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

projects/mysite/model_test/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return HttpResponse("hello this is index views")

projects/mysite/myapp/views.py
from django.shortcuts import render

# Create your views here.

projects/mysite/polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from polls.models import Poll, Choice
# Create your views here.


# def index(request):
#    latest_poll_list = Poll.objects.all()
#    template = loader.get_template('polls/index.html')
#    context = RequestContext(request, {
#        'latest_poll_list': latest_poll_list
#    })
#    # output = ', '.join([p.question for p in latest_poll_list])
#    return HttpResponse(template.render(context))

def index(request):
    latest_poll_list = Poll.objects.all()
    context = {'latest_poll_lists': latest_poll_list}

    return render(request, 'polls/index.html', context)


def details(request, poll_id):
    #return HttpResponse("poll_id is %s" % poll_id)
    #poll = get_object_or_404(Poll,poll_id)
    #return HttpResponse(poll_id)
    #return render(request,'polls/detail.html',poll)

    try:
        poll = Poll.objects.get(pk=poll_id)
    except Poll.DoesNotExist:
        raise Http404
    return render(request, 'polls/detail.html', {'poll': poll})


def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})


def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'poll': p,
             'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
        #return HttpResponse("You are voting on %s" % poll_id)


def w(request, wc):
    return HttpResponse("you are vistings %s" % wc)

projects/mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>{{ poll.question }}</h1>
{% comment %}{% if poll.choice_set.all %}
    {% for choice in poll.choice_set.all %}
        <li>choice.choice_text:{{ choice }}</li>
{% endcomment %}{% comment %}----这里之所以能够直接使用choice就能直接输出choice_text，是因为moels里面的__unicode__方法！  --{% endcomment %}{% comment %}
    {% endfor %}
{% endif %}{% endcomment %}


{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    {% endfor %}

<input type="submit" value="vote">
</form>

</body>
</html>

projects/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
{% if latest_poll_lists %}
    <ul>
        {% for poll in latest_poll_lists %}
                <li>question:<a href="{% url 'polls:details' poll.id %}">{{ poll.question }}</a> <span>-----发布于---{{ poll.pub_date.year }}年{{ poll.pub_date.month }}月{{ poll.pub_date.day }}日</span></li>
        {% endfor %}
    </ul>
{% else %}
    <p>NO polls are availble</p>
{% endif %}
</body>
</html>

projects/mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>{{ poll.question }}</h1>

<ul>
    {% comment %}奇怪，在这里访问的时候，poll.choice_set.all的时候不需要添加双括号（）{% endcomment %}
    {% for choice in poll.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:details' poll.id %}">Vote again?</a>
</body>
</html>